// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqqhxcwrdplokzgvsatf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxcWh4Y3dyZHBsb2t6Z3ZzYXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDY0MjcsImV4cCI6MjA3MDQ4MjQyN30.Hd2b8y624zf5odW1dMM80toV9ucbf0n5ujuZia2rTzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});